### ISSUE TITLE
1password + okta extensions don't load

### ISSUE THREAD

**Issue by yocontra** [samuelmaddock/electron-browser-shell#93] opened 2024-02-22 05:37 UTC
```
Loading extension from /Users/contra/Projects/canopy-app/.webpack/extensions/1Password-–-Password-Manager
(node:45189) ExtensionLoadWarning: Warnings loading extension at /Users/contra/Projects/canopy-app/.webpack/extensions/1Password-–-Password-Manager:
  Permission 'contextMenus' is unknown or URL pattern is malformed.
  Permission 'downloads' is unknown or URL pattern is malformed.
  Permission 'notifications' is unknown or URL pattern is malformed.
  Permission 'privacy' is unknown or URL pattern is malformed.
  Permission 'webNavigation' is unknown or URL pattern is malformed.

(Use `Electron --trace-warnings ...` to show where the warning was created)
Loading extension from /Users/contra/Projects/canopy-app/.webpack/extensions/Okta-Browser-Plugin
(node:45189) ExtensionLoadWarning: Warnings loading extension at /Users/contra/Projects/canopy-app/.webpack/extensions/Okta-Browser-Plugin:
  Permission 'cookies' is unknown or URL pattern is malformed.
  Permission 'webNavigation' is unknown or URL pattern is malformed.
  Permission 'privacy' is unknown or URL pattern is malformed.

[45189:0221/223357.417672:ERROR:extensions_browser_client.cc(68)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://kpeepjolgocnlfaehlhpkgmioincfjlf/background/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'onClicked')
  ID:      kpeepjolgocnlfaehlhpkgmioincfjlf
  Type:    RuntimeError
  Context: chrome-extension://kpeepjolgocnlfaehlhpkgmioincfjlf/background/background.js
  Stack Trace:
    {
      Line:     2
      Column:   1
      URL:      chrome-extension://kpeepjolgocnlfaehlhpkgmioincfjlf/background/background.js
      Function: (anonymous function)
    }
[45189:0221/223357.418611:ERROR:extensions_browser_client.cc(68)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 15
  ID:      kpeepjolgocnlfaehlhpkgmioincfjlf
  Type:    ManifestError
  ```

Attached zips for extensions. Let me know if there is anything I can do to assist, if you point me in the right direction I can work on fixing this and send a PR.

[Okta-Browser-Plugin.zip](https://github.com/samuelmaddock/electron-browser-shell/files/14369167/Okta-Browser-Plugin.zip)
[1Password-–-Password-Manager.zip](https://github.com/samuelmaddock/electron-browser-shell/files/14369168/1Password-.-Password-Manager.zip)

**Comment by yocontra** [comment] 2024-02-22 05:40
I realized these are probably just manifest v3 extensions - any idea where a good source for manifest v2 extensions would be as a short term solution until manifest v3 is supported?  #38

**Comment by samuelmaddock** [comment] 2024-02-23 00:10
Closing as these are caused by lack of Manifest v3 support.

To find v2 versions, you may have to search archives or the extension source repo if they save old releases.

**Closed by samuelmaddock** 2024-02-23 00:10 UTC
