### ISSUE TITLE
Extension icon

### ISSUE THREAD

**Issue by ggunia** [samuelmaddock/electron-browser-shell#48] opened 2021-11-24 08:54 UTC
## Problem

I'm loading the extension into the webContents with the persisted session.

But, I want to show the browser-action-list in the renderer app by specifying the session string:

**<browser-action-list partition="persist:custom"></browser-action-list>**

As a result, browser-action-list shows clickable rectangles and functionality works (It opens a window with the content of the extension browser action), but it **doesn't show the icon**.

We tried to load the same extensions in the defaultSession as well as in the persisted session, and it worked, but we would like to avoid this approach.

## Possible solution

As I understand registering a new protocol schema is required for fetching icons.

I think it should be possible to allow registering the **crx** protocol schema in the defaultSession, but grab the list of extensions from the given partition.

- - -

Looking forward to hear what you think would be the best way.

Happy to contribute

**Comment by samuelmaddock** [comment] 2021-11-30 05:06
Duplicate of https://github.com/samuelmaddock/electron-browser-shell/issues/41

**Closed by samuelmaddock** 2021-11-30 05:06 UTC
